config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'main#index'
  get 'attendees/new', as: "new"

  resources :attendees

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
	validates :first_name, :last_name, :email, presence: true
	validates :email, uniqueness: true
	validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]

  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
  end

  # GET /attendees/new
  def new
    @attendee = Attendee.new
  end

  # GET /attendees/1/edit
  def edit
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(attendee_params)

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @attendee, notice: "You've RSVP'd" }
        format.json { render :show, status: :created, location: @attendee }
      else
        format.html { render :new }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1
  # PATCH/PUT /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to attendees_url, notice: 'Attendee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:first_name, :last_name, :email)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :time, :location)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/attendees/_form.html.haml
= form_for @attendee do |f|
  - if @attendee.errors.any?
    #error_explanation
      %h2= "#{pluralize(@attendee.errors.count, "error")} prohibited this attendee from being saved:"
      %ul
        - @attendee.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :first_name, placeholder: "First Name", autofocus: true
  %br
  .field
    = f.text_field :last_name, placeholder: "Last Name", autofocus: true
  %br
  .field
    = f.text_field :email, placeholder: 'Email'
  %br
  .actions
    = f.submit 'Save'

app/views/attendees/edit.html.haml
.container.vertical-center
	%h1 Editing RSVP information

	= render 'form'

	= link_to 'Cancel', @attendee

app/views/attendees/index.html.haml
.container.vertical-center
  %h1 Guest List

  %table.center-table
    %thead
      %tr
        %th First
        %th Last
        %th
        %th
        %th

    %tbody
      - @attendees.each do |attendee|
        %tr
          %td= attendee.first_name
          %td= attendee.last_name
          -# %td= link_to 'Show', attendee
          -# %td= link_to 'Edit', edit_attendee_path(attendee)
          -# %td= link_to 'Destroy', attendee, :method => :delete, :data => { :confirm => 'Are you sure?' }
  %br
  %p.small *Email addresses are only visible to administrators for privacy

  = link_to 'RSVP', new_attendee_path
  = link_to 'Home', root_path

app/views/attendees/new.html.haml
.container.vertical-center
	%h1 New RSVP
	%br
	= render 'form'

	= link_to 'Cancel', root_path

app/views/attendees/show.html.haml
.container.vertical-center
  %p#notice= notice

  %p
    %b Name:
    = @attendee.first_name + " " + @attendee.last_name
  %p
    %b Email:
    = @attendee.email

  = link_to 'Edit', edit_attendee_path(@attendee)
  = link_to 'Delete', @attendee, :method => :delete
  = link_to 'Home', root_path

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :time
    = f.time_select :time
  .field
    = f.label :location
    = f.text_field :location
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table
  %thead
    %tr
      %th Name
      %th Date
      %th Time
      %th Location
      %th
      %th
      %th

  %tbody
    - @events.each do |event|
      %tr
        %td= event.name
        %td= event.date
        %td= event.time
        %td= event.location
        %td= link_to 'Show', event
        %td= link_to 'Edit', edit_event_path(event)
        %td= link_to 'Destroy', event, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @event.name
%p
  %b Date:
  = @event.date
%p
  %b Time:
  = @event.time
%p
  %b Location:
  = @event.location

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/layouts/application.haml
!!!
%html
  %head
    %title Fotonic RSVP
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/main/index.html.haml
.container.cover.vertical-center
  .col-xs-12
  %h1 You're Invited
  .row
  .col-xs-6
  %h1 RSVP
  %p A Sample RSVP Application
  = link_to 'RSVP', new_attendee_path
  = link_to 'Guest List', attendees_path


  -# %button= link_to 'RSVP', new_attendee_path
  -# %button= link_to 'Guest List', attendees_path